### ISSUE TITLE
Image Management Separation

### ISSUE THREAD

**Issue by brhoades** [grade-it/grader#4]
Let's create a separate script, image.py, which will handle assignment image creation and manipulation.

    USAGE: python image.py [ARGS] name
    $ python image.py create [--tags tag1,tag2,tag3] [--template tempatename] [--dockerfile dockerfile] [--extra extrafile,extrafolder] imagename
    $ python image.py remove [--cascade] name

**Comment by michaelwisely** [comment]
I think this is irrelevant now? It's kind of rolled into `grader build`

**Comment by brhoades** [comment]
Sure is...
